# Generated by Django 4.0.3 on 2022-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='editorial',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Imagen de producto'),
        ),
        migrations.AddField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
