# Generated by Django 3.2.13 on 2022-07-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220622_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='numero_block',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='numero_calle',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='boleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.boleta'),
        ),
    ]
