# Generated by Django 4.0.3 on 2022-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shippingaddress_block_number_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='comuna',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
