# Generated by Django 4.0.3 on 2022-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shippingaddress_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
