# Generated by Django 4.0.3 on 2022-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rut',
        ),
    ]
